version: '3.9.7'

services:
  backend:
    build: ./Authentifcation_Verif_Email
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./frontend-application
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
