---
- name: Déploiement Docker de l’application Spring Boot
  hosts: docker
  become: true
  tasks:
    - name: Arrêter et supprimer le conteneur existant
      docker_container:
        name: verifmail
        state: absent  
    - name: Lancer le conteneur avec la nouvelle image
      docker_container:
        name: verifmail
        image: souhirks/verifmail
        ports: 
            -"8080:8080"
        state: started 
