apiVersion: apps/v1
kind: Deployment
metadata:
  name: verifmail
spec:
  replicas: 2
  selector:
    matchLabels:
      app: souhir
  template:
    metadata:
      labels:
        app: souhir
    spec:
      containers:
        - name: verifmail
          image: souhirks/verifmail
---
apiVersion: v1
kind: Service
metadata:
  name: souhirverifmailsvc
spec:
  type: NodePort
  selector:
    app: souhir
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30110
